name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Go fmt check
        run: |
          test -z "$(gofmt -l .)" || (gofmt -l . && exit 1)
        shell: bash
      - name: Go test
        run: go test ./...
